name: 'Terraform'

on:
  push:
    branches:
      - main  
  pull_request:
    #paths:
    #- 'terraform/**'
    #- 'terraform-e2e-ci/**'
    #- '.github/workflows/terraform*'

jobs:
  # main config
  main:
    name: 'main'
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'checkout'
      uses: 'actions/checkout@v2'

    - name: 'setup-terraform'
      uses: 'hashicorp/setup-terraform@v1'
      with:
        terraform_version: '0.14.5'

    - name: 'init'
      #working-directory: './terraform'
      run: 'terraform init'

    - name: 'validate'
      #working-directory: './terraform'
      run: 'terraform validate'

    - name: 'fmt'
      #working-directory: './terraform'
      run: 'terraform fmt -diff -check'
