name: 'Terraform'

on:
  push:
    branches:
      - main  
  pull_request:
    #paths:
    #- 'terraform/**'
    #- 'terraform-e2e-ci/**'
    #- '.github/workflows/terraform*'

concurrency: terraform-${{ github.ref }}

jobs:
  # main config
  main:
    name: 'main'
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'checkout'
      uses: 'actions/checkout@v2'

    - name: 'Setup Terraform'
      uses: 'hashicorp/setup-terraform@v1'
      with:
        terraform_version: '0.14.5'

    - name: 'Terraform Init'
      run: 'terraform init'

    - name: TF Lint
      uses: reviewdog/action-tflint@v1.17.0
      with:
        github_token: ${{ secrets.github_token }}
        fail_on_error: "true"
        filter_mode: "nofilter"
        level: "warning"

    - name: 'Terraform Validate'
      run: 'terraform validate -no-color'

    - name: 'fmt'
      #working-directory: './terraform'
      run: 'terraform fmt -diff -check'
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
